### ISSUE TITLE
Adrian's Wishlist from migration

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/polyphemus#1]
@sampsyo mentioned the following

Alright, here are some concrete steps I had in mind:

- [x] Resolve or decide to move any open PRs—perhaps that's just #242 and #240 at the moment. (And #240 is 100% ready to go, I think?)
- [x] Move the `buildbot` directory to a new repository.
- [x] Delete the Dockerfile from this repository. We'll probably just start from scratch in the new repo.
- [x] Delete the Seashell stage and the "no-Seashell" job config option from the Buildbot.
- [ ] Bring [our local config stuff](https://github.com/cucapra/seashell-gorgonzola) up to speed with the new repo.
- [X] Move any relevant issues to the new repo from this one.

And mostly as a note to myself, here are a few issues I was intending to create in the new repo once it exists:

- Make a workflow for packaging the Buildbot as an AMI for easy deployment, including on non-F1 instances if you don't actually want to run stuff (it's cheaper!).
- @ViviYe has talked about adding a "delete" button to jobs to free up space.
- Not the highest priority, but: lots of operations will slow down linearly with the number of jobs because they scan the entire database; cutting down on this would be awesome.
- Feature request: "priority" jobs that jump the queue and run immediately for interactive execution. A client CLI tool could help submit jobs and wait for their results, streaming the log interactively, to sort of simulate the feeling of running commands on your own machine.

**Comment by sampsyo** [comment]
Cool! Migrated my wishlist to discrete issues. I'll take care of the Docker stuff.
