### ISSUE TITLE
Generate AMIs for easy bringup

### ISSUE THREAD

**Issue by sampsyo** [cucapra/polyphemus#3]
Because Buildbot can now run on EC2, let's find out how hard it would be to build and publish AMIs! An AMI would make it easy to start a server with everything you need to build stuff.

As an added bonus, we should target both F1 and non-F1 instances based on the [FPGA Developer AMI](https://aws.amazon.com/marketplace/pp/B06VVYBLZZ), if possible. Non-F1 instances are much cheaper and can suffice if you just want to synthesize designs, not run them.

(Expanded from #1.)

**Comment by rachitnigam** [comment]
Generating AMI from EC2 instances seems [pretty easy](https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/tkv-create-ami-from-instance.html).

Now that @ViviYe and I have experimented with the developer AMI, we can look into exporting it.

**Comment by sampsyo** [comment]
As a stretch goal, maybe we can someday have a mechanism for starting and stopping instances "on demand" when there are jobs to process, sort of like [Chazz](https://github.com/cucapra/chazz) is for HammerBlade…

**Comment by rachitnigam** [comment]
Created an AMI for the compile workers in AWS.
