### ISSUE TITLE
Why is sh -c used?

### ISSUE THREAD

**Issue by sa2257** [cucapra/polyphemus#35]
I’m curious why `sh -c` is used to run emulation and hardware execution in SDACCEL flow. It might be useful for the execution issue I have in Vitis. Thanks!

https://github.com/cucapra/polyphemus/blob/a7c3eeba67a35b95920f066347524bbe49259d76/polyphemus/worker_f1.py#L212

**Comment by sampsyo** [comment]
Otherwise you can't use `source` or `;`, which are shell constructs (not literal executables).
